server:
    port: 8080
spring:
    application:
        name: local-grpc-client

grpc:
    client:
        greet-server:
            address: 'static://127.0.0.1:9898'
            enableKeepAlive: true
            keepAliveWithoutCalls: true
            negotiationType: plaintext
